### PR TITLE
implemented changes to move to deal.II version 9.6.0

### PR DESCRIPTION
**Pull request by andreamola**
Also a test on 64-bit dof handler had to be changed. Both standard output and test source code had to be fixed

### CODE REVIEW

**Comment by andreamola** [comment]
Mmm, before pushing I ran the indent script in the /scripts folder. So it is odd that now indent is all messed up. Do we need to change/update the indent script?

**Review by luca-heltai — APPROVED** [review]

**Comment by luca-heltai** [comment]
Are you planning to make similar changes to make WaveBEM work with this new version of pi-BEM?

**Comment by andreamola** [comment]
Thanks a lot Luca, for the fix and the merge.
As of now, we have two different codes that are based on pi-BEM. One is
pi-BEM-free_surface (the new version of waveBEM,
https://www.sciencedirect.com/science/article/pii/S0307904X23002445), and
the other is wingbem (the solver for lifting surfaces such as hydrofoils,
https://arxiv.org/abs/2410.10529). Of course I am also updating both of
them to deal.II 9.6. If you want I can tell you more about both projects.
As for waveBEM itself, it is not using/linking to pi-BEM, and I am not
really developing/maintaining it any more. The new free surface model is
much better, and allows for steady simulations too. Plus, the new code is
fully parallel and works way better.

       Andrea

**Comment by luca-heltai** [comment]
You should advertize this on the mailing list (there are many users wanting to use WaveBEM), or you should point the old WaveBEM to the new software. :)

**Pull request merged**
